# Generated by Copilot on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("terminated", "Terminated"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
